CREATE USER 'ANBK010x' WITH INHERIT IN ROLE cwa_ppdd_flyway ENCRYPTED PASSWORD 'CLvzCwm3';
CREATE USER "uqoAzah" WITH INHERIT IN ROLE cwa_data_ppac ENCRYPTED PASSWORD 'Iv6GZhlv';
CREATE USER "FpIjZ6gD" WITH INHERIT IN ROLE cwa_data_edus ENCRYPTED PASSWORD 'BxnwMKGO';
